# Generated by Django 3.2.3 on 2021-07-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes', models.BooleanField()),
                ('no', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DeletePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes', models.BooleanField()),
                ('no', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EditPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_question', models.TextField()),
                ('poll_option1', models.CharField(max_length=50)),
                ('poll_option2', models.CharField(max_length=50)),
                ('poll_option3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_question', models.TextField()),
                ('poll_option1', models.CharField(max_length=50)),
                ('poll_option2', models.CharField(max_length=50)),
                ('poll_option3', models.CharField(max_length=50)),
                ('poll_option1_count', models.IntegerField(default=0)),
                ('poll_option2_count', models.IntegerField(default=0)),
                ('poll_option3_count', models.IntegerField(default=0)),
            ],
        ),
    ]
